import { BusinessCategory, CategoryInfo } from './types';

// Comprehensive business category configuration
export const CATEGORY_CONFIG: Record<BusinessCategory, CategoryInfo> = {
  // Home Services
  plumber: {
    displayName: 'Plumber',
    keywords: ['plumber', 'plumbing', 'pipe', 'drain', 'water heater', 'toilet', 'faucet', 'leak'],
    redditSearchTerms: ['plumber recommendation', 'plumbing help', 'need plumber', 'plumber near'],
    avgTicket: 350,
    afterHoursPercent: 38,
    avgMonthlySearches: { small: 800, medium: 2200, large: 5500 },
  },
  electrician: {
    displayName: 'Electrician',
    keywords: ['electrician', 'electrical', 'wiring', 'outlet', 'breaker', 'panel', 'electric'],
    redditSearchTerms: ['electrician recommendation', 'electrical work', 'need electrician'],
    avgTicket: 280,
    afterHoursPercent: 32,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4200 },
  },
  hvac_contractor: {
    displayName: 'HVAC',
    keywords: ['hvac', 'heating', 'cooling', 'air conditioning', 'ac', 'furnace', 'heat pump'],
    redditSearchTerms: ['hvac recommendation', 'ac repair', 'heating repair', 'furnace'],
    avgTicket: 420,
    afterHoursPercent: 42,
    avgMonthlySearches: { small: 700, medium: 2000, large: 4800 },
  },
  locksmith: {
    displayName: 'Locksmith',
    keywords: ['locksmith', 'lock', 'key', 'locked out', 'deadbolt', 'rekey'],
    redditSearchTerms: ['locksmith recommendation', 'locked out', 'need locksmith'],
    avgTicket: 180,
    afterHoursPercent: 55,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  roofing_contractor: {
    displayName: 'Roofer',
    keywords: ['roofing', 'roofer', 'roof', 'shingles', 'gutter'],
    redditSearchTerms: ['roofer recommendation', 'roof repair', 'roofing company'],
    avgTicket: 8500,
    afterHoursPercent: 22,
    avgMonthlySearches: { small: 500, medium: 1400, large: 3500 },
  },
  moving_company: {
    displayName: 'Moving Company',
    keywords: ['moving', 'mover', 'relocation', 'hauling'],
    redditSearchTerms: ['moving company recommendation', 'movers', 'need movers'],
    avgTicket: 1200,
    afterHoursPercent: 28,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  painter: {
    displayName: 'Painter',
    keywords: ['painter', 'painting', 'house painter', 'interior painting', 'exterior painting'],
    redditSearchTerms: ['painter recommendation', 'house painting', 'need painter'],
    avgTicket: 2500,
    afterHoursPercent: 18,
    avgMonthlySearches: { small: 450, medium: 1300, large: 3200 },
  },
  landscaper: {
    displayName: 'Landscaper',
    keywords: ['landscaper', 'landscaping', 'lawn', 'yard', 'garden', 'lawn care'],
    redditSearchTerms: ['landscaper recommendation', 'lawn care', 'landscaping company'],
    avgTicket: 450,
    afterHoursPercent: 15,
    avgMonthlySearches: { small: 550, medium: 1600, large: 4000 },
  },
  pest_control: {
    displayName: 'Pest Control',
    keywords: ['pest control', 'exterminator', 'bugs', 'mice', 'rats', 'termites', 'ants'],
    redditSearchTerms: ['pest control recommendation', 'exterminator', 'bug problem'],
    avgTicket: 250,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  cleaning_service: {
    displayName: 'Cleaning Service',
    keywords: ['cleaning', 'cleaner', 'maid', 'housekeeping', 'deep clean', 'janitorial'],
    redditSearchTerms: ['cleaning service recommendation', 'house cleaner', 'maid service'],
    avgTicket: 180,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 650, medium: 1900, large: 4600 },
  },
  handyman: {
    displayName: 'Handyman',
    keywords: ['handyman', 'handy man', 'repairs', 'fix', 'maintenance'],
    redditSearchTerms: ['handyman recommendation', 'need handyman', 'home repairs'],
    avgTicket: 220,
    afterHoursPercent: 30,
    avgMonthlySearches: { small: 700, medium: 2100, large: 5000 },
  },
  garage_door: {
    displayName: 'Garage Door',
    keywords: ['garage door', 'garage opener', 'overhead door'],
    redditSearchTerms: ['garage door repair', 'garage door company'],
    avgTicket: 380,
    afterHoursPercent: 45,
    avgMonthlySearches: { small: 350, medium: 1000, large: 2500 },
  },
  tree_service: {
    displayName: 'Tree Service',
    keywords: ['tree service', 'tree removal', 'tree trimming', 'arborist', 'stump'],
    redditSearchTerms: ['tree service recommendation', 'tree removal', 'arborist'],
    avgTicket: 650,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 400, medium: 1200, large: 2800 },
  },
  towing: {
    displayName: 'Towing',
    keywords: ['towing', 'tow truck', 'roadside assistance', 'tow'],
    redditSearchTerms: ['towing company recommendation', 'tow truck', 'roadside help'],
    avgTicket: 150,
    afterHoursPercent: 60,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  appliance_repair: {
    displayName: 'Appliance Repair',
    keywords: ['appliance repair', 'washer repair', 'dryer repair', 'refrigerator', 'dishwasher'],
    redditSearchTerms: ['appliance repair recommendation', 'washer repair', 'fridge repair'],
    avgTicket: 220,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 450, medium: 1400, large: 3400 },
  },

  // Food & Dining
  restaurant: {
    displayName: 'Restaurant',
    keywords: ['restaurant', 'dining', 'eatery', 'cuisine', 'dine'],
    redditSearchTerms: ['restaurant recommendation', 'best restaurant', 'where to eat', 'food recommendation'],
    avgTicket: 40,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 2000, medium: 6000, large: 15000 },
  },
  // Specific Asian restaurants with realistic pricing
  dumpling_restaurant: {
    displayName: 'Dumpling Restaurant',
    keywords: ['dumpling', 'dumplings', 'jiaozi', 'gyoza', 'momo', 'xiaolongbao', 'soup dumpling', 'potsticker'],
    redditSearchTerms: ['dumpling restaurant', 'best dumplings', 'dumpling near'],
    avgTicket: 18,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  noodle_restaurant: {
    displayName: 'Noodle Shop',
    keywords: ['noodle', 'noodles', 'ramen', 'pho', 'udon', 'soba', 'lo mein', 'chow mein', 'pad thai', 'bun bo', 'laksa'],
    redditSearchTerms: ['noodle shop', 'best noodles', 'ramen near', 'pho near'],
    avgTicket: 16,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  ramen_restaurant: {
    displayName: 'Ramen Shop',
    keywords: ['ramen', 'tonkotsu', 'miso ramen', 'shoyu ramen'],
    redditSearchTerms: ['ramen restaurant', 'best ramen', 'ramen near'],
    avgTicket: 18,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  pho_restaurant: {
    displayName: 'Pho Restaurant',
    keywords: ['pho', 'vietnamese noodle'],
    redditSearchTerms: ['pho restaurant', 'best pho', 'vietnamese noodle'],
    avgTicket: 15,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  sushi_restaurant: {
    displayName: 'Sushi Restaurant',
    keywords: ['sushi', 'sashimi', 'omakase', 'maki', 'nigiri'],
    redditSearchTerms: ['sushi restaurant', 'best sushi', 'sushi near'],
    avgTicket: 45,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  dim_sum_restaurant: {
    displayName: 'Dim Sum Restaurant',
    keywords: ['dim sum', 'dimsum', 'yum cha', 'har gow', 'siu mai', 'char siu bao'],
    redditSearchTerms: ['dim sum', 'best dim sum', 'dim sum near'],
    avgTicket: 28,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 300, medium: 900, large: 2200 },
  },
  chinese_restaurant: {
    displayName: 'Chinese Restaurant',
    keywords: ['chinese', 'szechuan', 'sichuan', 'cantonese', 'hunan', 'wok'],
    redditSearchTerms: ['chinese restaurant', 'best chinese food', 'chinese near'],
    avgTicket: 22,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  thai_restaurant: {
    displayName: 'Thai Restaurant',
    keywords: ['thai', 'pad thai', 'curry', 'tom yum'],
    redditSearchTerms: ['thai restaurant', 'best thai food', 'thai near'],
    avgTicket: 20,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  vietnamese_restaurant: {
    displayName: 'Vietnamese Restaurant',
    keywords: ['vietnamese', 'banh mi', 'bun', 'spring roll'],
    redditSearchTerms: ['vietnamese restaurant', 'best vietnamese', 'vietnamese near'],
    avgTicket: 18,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  korean_restaurant: {
    displayName: 'Korean Restaurant',
    keywords: ['korean', 'bibimbap', 'bulgogi', 'kbbq', 'korean bbq', 'kimchi'],
    redditSearchTerms: ['korean restaurant', 'korean bbq', 'korean near'],
    avgTicket: 28,
    afterHoursPercent: 45,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  indian_restaurant: {
    displayName: 'Indian Restaurant',
    keywords: ['indian', 'curry', 'tandoori', 'naan', 'biryani', 'masala'],
    redditSearchTerms: ['indian restaurant', 'best indian food', 'indian near'],
    avgTicket: 22,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  japanese_restaurant: {
    displayName: 'Japanese Restaurant',
    keywords: ['japanese', 'izakaya', 'teriyaki', 'tempura', 'bento'],
    redditSearchTerms: ['japanese restaurant', 'japanese food', 'japanese near'],
    avgTicket: 35,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  mexican_restaurant: {
    displayName: 'Mexican Restaurant',
    keywords: ['mexican', 'tacos', 'taco', 'burrito', 'quesadilla', 'enchilada', 'taqueria'],
    redditSearchTerms: ['mexican restaurant', 'best tacos', 'mexican near'],
    avgTicket: 18,
    afterHoursPercent: 45,
    avgMonthlySearches: { small: 1000, medium: 3000, large: 7500 },
  },
  pizza_restaurant: {
    displayName: 'Pizza Restaurant',
    keywords: ['pizza', 'pizzeria', 'pie'],
    redditSearchTerms: ['pizza restaurant', 'best pizza', 'pizza near'],
    avgTicket: 25,
    afterHoursPercent: 50,
    avgMonthlySearches: { small: 1200, medium: 3600, large: 9000 },
  },
  burger_restaurant: {
    displayName: 'Burger Restaurant',
    keywords: ['burger', 'hamburger', 'cheeseburger'],
    redditSearchTerms: ['burger restaurant', 'best burger', 'burger near'],
    avgTicket: 16,
    afterHoursPercent: 45,
    avgMonthlySearches: { small: 1000, medium: 3000, large: 7500 },
  },
  fast_food: {
    displayName: 'Fast Food',
    keywords: ['fast food', 'drive thru', 'drive-thru', 'quick service'],
    redditSearchTerms: ['fast food', 'quick food'],
    avgTicket: 12,
    afterHoursPercent: 55,
    avgMonthlySearches: { small: 1500, medium: 4500, large: 12000 },
  },
  sandwich_restaurant: {
    displayName: 'Sandwich Shop',
    keywords: ['sandwich', 'sub', 'deli', 'hoagie', 'panini'],
    redditSearchTerms: ['sandwich shop', 'best sandwich', 'deli near'],
    avgTicket: 14,
    afterHoursPercent: 30,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  italian_restaurant: {
    displayName: 'Italian Restaurant',
    keywords: ['italian', 'pasta', 'trattoria', 'ristorante', 'risotto', 'gnocchi'],
    redditSearchTerms: ['italian restaurant', 'best italian', 'italian near'],
    avgTicket: 35,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  seafood_restaurant: {
    displayName: 'Seafood Restaurant',
    keywords: ['seafood', 'fish', 'oyster', 'crab', 'lobster', 'shrimp'],
    redditSearchTerms: ['seafood restaurant', 'best seafood', 'seafood near'],
    avgTicket: 45,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  steakhouse: {
    displayName: 'Steakhouse',
    keywords: ['steakhouse', 'steak house', 'chophouse', 'prime rib'],
    redditSearchTerms: ['steakhouse', 'best steak', 'steak near'],
    avgTicket: 65,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  breakfast_restaurant: {
    displayName: 'Breakfast Restaurant',
    keywords: ['breakfast', 'brunch', 'pancake', 'waffle', 'diner'],
    redditSearchTerms: ['breakfast restaurant', 'best brunch', 'breakfast near'],
    avgTicket: 18,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  cafe: {
    displayName: 'Cafe',
    keywords: ['cafe', 'coffee', 'espresso', 'coffee shop', 'coffeehouse'],
    redditSearchTerms: ['coffee shop recommendation', 'best cafe', 'coffee near'],
    avgTicket: 12,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 1500, medium: 4500, large: 12000 },
  },
  bakery: {
    displayName: 'Bakery',
    keywords: ['bakery', 'bread', 'pastry', 'cake', 'baked goods', 'pastries'],
    redditSearchTerms: ['bakery recommendation', 'best bakery', 'cake shop', 'pastry'],
    avgTicket: 25,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  bar: {
    displayName: 'Bar',
    keywords: ['bar', 'pub', 'tavern', 'lounge', 'cocktail', 'nightclub'],
    redditSearchTerms: ['bar recommendation', 'best bar', 'cocktail bar', 'pub'],
    avgTicket: 35,
    afterHoursPercent: 70,
    avgMonthlySearches: { small: 1200, medium: 3500, large: 9000 },
  },
  food_truck: {
    displayName: 'Food Truck',
    keywords: ['food truck', 'street food', 'mobile food'],
    redditSearchTerms: ['food truck recommendation', 'best food truck'],
    avgTicket: 15,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  catering: {
    displayName: 'Catering',
    keywords: ['catering', 'caterer', 'event food', 'party food'],
    redditSearchTerms: ['catering recommendation', 'caterer for event', 'wedding catering'],
    avgTicket: 1500,
    afterHoursPercent: 45,
    avgMonthlySearches: { small: 300, medium: 900, large: 2200 },
  },

  // Health & Wellness
  gym: {
    displayName: 'Gym',
    keywords: ['gym', 'fitness', 'workout', 'fitness center', 'health club'],
    redditSearchTerms: ['gym recommendation', 'best gym', 'fitness center'],
    avgTicket: 50,
    afterHoursPercent: 45,
    avgMonthlySearches: { small: 1000, medium: 3000, large: 7500 },
  },
  yoga_studio: {
    displayName: 'Yoga Studio',
    keywords: ['yoga', 'yoga studio', 'pilates', 'meditation'],
    redditSearchTerms: ['yoga studio recommendation', 'yoga class', 'pilates'],
    avgTicket: 20,
    afterHoursPercent: 30,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  spa: {
    displayName: 'Spa',
    keywords: ['spa', 'day spa', 'wellness', 'facial', 'body treatment'],
    redditSearchTerms: ['spa recommendation', 'best spa', 'day spa'],
    avgTicket: 120,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 500, medium: 1500, large: 4000 },
  },
  massage: {
    displayName: 'Massage',
    keywords: ['massage', 'massage therapy', 'therapeutic massage', 'bodywork'],
    redditSearchTerms: ['massage recommendation', 'massage therapist', 'best massage'],
    avgTicket: 90,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  chiropractor: {
    displayName: 'Chiropractor',
    keywords: ['chiropractor', 'chiropractic', 'spine', 'back pain', 'adjustment'],
    redditSearchTerms: ['chiropractor recommendation', 'best chiropractor', 'back pain'],
    avgTicket: 75,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  dentist: {
    displayName: 'Dentist',
    keywords: ['dentist', 'dental', 'teeth', 'orthodontist', 'oral'],
    redditSearchTerms: ['dentist recommendation', 'best dentist', 'dental clinic'],
    avgTicket: 200,
    afterHoursPercent: 15,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  doctor: {
    displayName: 'Doctor',
    keywords: ['doctor', 'physician', 'clinic', 'medical', 'healthcare', 'urgent care'],
    redditSearchTerms: ['doctor recommendation', 'best doctor', 'primary care'],
    avgTicket: 150,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 1000, medium: 3000, large: 7500 },
  },
  veterinarian: {
    displayName: 'Veterinarian',
    keywords: ['veterinarian', 'vet', 'animal hospital', 'pet clinic', 'animal doctor'],
    redditSearchTerms: ['vet recommendation', 'best veterinarian', 'animal hospital', 'pet doctor'],
    avgTicket: 120,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },

  // Beauty & Personal Care
  hair_salon: {
    displayName: 'Hair Salon',
    keywords: ['hair salon', 'hairdresser', 'stylist', 'haircut', 'hair color', 'salon'],
    redditSearchTerms: ['hair salon recommendation', 'best hairdresser', 'haircut near'],
    avgTicket: 65,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 1200, medium: 3600, large: 9000 },
  },
  barber: {
    displayName: 'Barber',
    keywords: ['barber', 'barbershop', 'haircut', 'fade', 'mens haircut'],
    redditSearchTerms: ['barber recommendation', 'best barbershop', 'barber near'],
    avgTicket: 30,
    afterHoursPercent: 15,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  nail_salon: {
    displayName: 'Nail Salon',
    keywords: ['nail salon', 'manicure', 'pedicure', 'nails', 'nail spa'],
    redditSearchTerms: ['nail salon recommendation', 'best nail salon', 'manicure'],
    avgTicket: 45,
    afterHoursPercent: 15,
    avgMonthlySearches: { small: 700, medium: 2100, large: 5200 },
  },
  beauty_salon: {
    displayName: 'Beauty Salon',
    keywords: ['beauty salon', 'beauty', 'aesthetics', 'skincare', 'facial'],
    redditSearchTerms: ['beauty salon recommendation', 'aesthetician', 'facial'],
    avgTicket: 80,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  tattoo: {
    displayName: 'Tattoo Shop',
    keywords: ['tattoo', 'tattoo shop', 'tattoo artist', 'piercing', 'ink'],
    redditSearchTerms: ['tattoo artist recommendation', 'best tattoo shop', 'tattoo near'],
    avgTicket: 250,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },

  // Retail
  retail_store: {
    displayName: 'Retail Store',
    keywords: ['store', 'shop', 'retail', 'boutique'],
    redditSearchTerms: ['shop recommendation', 'best store', 'where to buy'],
    avgTicket: 75,
    afterHoursPercent: 30,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  clothing_store: {
    displayName: 'Clothing Store',
    keywords: ['clothing', 'apparel', 'fashion', 'clothes', 'boutique'],
    redditSearchTerms: ['clothing store recommendation', 'boutique', 'fashion'],
    avgTicket: 100,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  jewelry_store: {
    displayName: 'Jewelry Store',
    keywords: ['jewelry', 'jeweler', 'rings', 'watches', 'diamonds'],
    redditSearchTerms: ['jewelry store recommendation', 'best jeweler', 'engagement ring'],
    avgTicket: 500,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  florist: {
    displayName: 'Florist',
    keywords: ['florist', 'flowers', 'floral', 'bouquet', 'flower shop'],
    redditSearchTerms: ['florist recommendation', 'best flowers', 'flower delivery'],
    avgTicket: 65,
    afterHoursPercent: 30,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  pet_store: {
    displayName: 'Pet Store',
    keywords: ['pet store', 'pet shop', 'pet supplies', 'pet food'],
    redditSearchTerms: ['pet store recommendation', 'best pet shop', 'pet supplies'],
    avgTicket: 45,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },

  // Auto
  auto_repair: {
    displayName: 'Auto Repair',
    keywords: ['auto repair', 'mechanic', 'car repair', 'auto shop', 'automotive'],
    redditSearchTerms: ['mechanic recommendation', 'auto repair', 'car mechanic', 'honest mechanic'],
    avgTicket: 450,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  car_wash: {
    displayName: 'Car Wash',
    keywords: ['car wash', 'auto detailing', 'detailing', 'car cleaning'],
    redditSearchTerms: ['car wash recommendation', 'auto detailing', 'best car wash'],
    avgTicket: 35,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  auto_dealer: {
    displayName: 'Auto Dealer',
    keywords: ['car dealer', 'auto dealer', 'car dealership', 'used cars'],
    redditSearchTerms: ['car dealer recommendation', 'where to buy car', 'car dealership'],
    avgTicket: 25000,
    afterHoursPercent: 35,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  tire_shop: {
    displayName: 'Tire Shop',
    keywords: ['tire shop', 'tires', 'tire service', 'wheel'],
    redditSearchTerms: ['tire shop recommendation', 'best tires', 'tire service'],
    avgTicket: 400,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },

  // Professional Services
  lawyer: {
    displayName: 'Lawyer',
    keywords: ['lawyer', 'attorney', 'law firm', 'legal', 'counsel'],
    redditSearchTerms: ['lawyer recommendation', 'attorney', 'legal help', 'need lawyer'],
    avgTicket: 350,
    afterHoursPercent: 30,
    avgMonthlySearches: { small: 600, medium: 1800, large: 4500 },
  },
  accountant: {
    displayName: 'Accountant',
    keywords: ['accountant', 'cpa', 'tax', 'bookkeeper', 'accounting'],
    redditSearchTerms: ['accountant recommendation', 'cpa', 'tax help', 'bookkeeper'],
    avgTicket: 250,
    afterHoursPercent: 25,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  real_estate: {
    displayName: 'Real Estate',
    keywords: ['real estate', 'realtor', 'realty', 'property', 'broker'],
    redditSearchTerms: ['realtor recommendation', 'real estate agent', 'buying house'],
    avgTicket: 8000,
    afterHoursPercent: 45,
    avgMonthlySearches: { small: 800, medium: 2400, large: 6000 },
  },
  insurance: {
    displayName: 'Insurance',
    keywords: ['insurance', 'insurance agent', 'coverage', 'policy'],
    redditSearchTerms: ['insurance recommendation', 'insurance agent', 'best insurance'],
    avgTicket: 150,
    afterHoursPercent: 20,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  photography: {
    displayName: 'Photography',
    keywords: ['photographer', 'photography', 'photo', 'portrait', 'wedding photographer'],
    redditSearchTerms: ['photographer recommendation', 'wedding photographer', 'portrait photographer'],
    avgTicket: 400,
    afterHoursPercent: 40,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },

  // Other
  hotel: {
    displayName: 'Hotel',
    keywords: ['hotel', 'motel', 'inn', 'lodging', 'accommodation'],
    redditSearchTerms: ['hotel recommendation', 'where to stay', 'best hotel'],
    avgTicket: 150,
    afterHoursPercent: 60,
    avgMonthlySearches: { small: 1000, medium: 3000, large: 7500 },
  },
  daycare: {
    displayName: 'Daycare',
    keywords: ['daycare', 'childcare', 'preschool', 'nursery', 'child care'],
    redditSearchTerms: ['daycare recommendation', 'childcare', 'preschool'],
    avgTicket: 1200,
    afterHoursPercent: 15,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
  tutoring: {
    displayName: 'Tutoring',
    keywords: ['tutor', 'tutoring', 'learning center', 'education'],
    redditSearchTerms: ['tutor recommendation', 'tutoring', 'math tutor'],
    avgTicket: 60,
    afterHoursPercent: 50,
    avgMonthlySearches: { small: 400, medium: 1200, large: 3000 },
  },
  music_lessons: {
    displayName: 'Music Lessons',
    keywords: ['music lessons', 'music school', 'piano lessons', 'guitar lessons', 'music teacher'],
    redditSearchTerms: ['music lessons recommendation', 'piano teacher', 'guitar lessons'],
    avgTicket: 50,
    afterHoursPercent: 55,
    avgMonthlySearches: { small: 300, medium: 900, large: 2200 },
  },
  other: {
    displayName: 'Business',
    keywords: [],
    redditSearchTerms: ['recommendation', 'best', 'looking for'],
    avgTicket: 100,
    afterHoursPercent: 30,
    avgMonthlySearches: { small: 500, medium: 1500, large: 3800 },
  },
};

// Google Places type to our category mapping
const GOOGLE_TYPE_MAPPING: Record<string, BusinessCategory> = {
  // Home Services
  plumber: 'plumber',
  electrician: 'electrician',
  hvac_contractor: 'hvac_contractor',
  heating_contractor: 'hvac_contractor',
  air_conditioning_contractor: 'hvac_contractor',
  locksmith: 'locksmith',
  roofing_contractor: 'roofing_contractor',
  moving_company: 'moving_company',
  painter: 'painter',
  house_painter: 'painter',
  landscaper: 'landscaper',
  lawn_care_service: 'landscaper',
  pest_control_service: 'pest_control',
  cleaning_service: 'cleaning_service',
  house_cleaning_service: 'cleaning_service',
  handyman: 'handyman',
  garage_door_supplier: 'garage_door',
  tree_service: 'tree_service',
  towing_service: 'towing',
  appliance_repair_service: 'appliance_repair',

  // Food & Dining - Specific types with realistic pricing
  restaurant: 'restaurant',
  american_restaurant: 'restaurant',

  // Asian restaurants with realistic pricing
  dumpling_restaurant: 'dumpling_restaurant',
  noodle_restaurant: 'noodle_restaurant',
  ramen_restaurant: 'ramen_restaurant',
  pho_restaurant: 'pho_restaurant',
  chinese_restaurant: 'chinese_restaurant',
  japanese_restaurant: 'japanese_restaurant',
  sushi_restaurant: 'sushi_restaurant',
  thai_restaurant: 'thai_restaurant',
  indian_restaurant: 'indian_restaurant',
  vietnamese_restaurant: 'vietnamese_restaurant',
  korean_restaurant: 'korean_restaurant',
  dim_sum_restaurant: 'dim_sum_restaurant',

  // Other cuisines
  italian_restaurant: 'italian_restaurant',
  mexican_restaurant: 'mexican_restaurant',
  mediterranean_restaurant: 'restaurant',
  french_restaurant: 'restaurant',
  greek_restaurant: 'restaurant',
  spanish_restaurant: 'restaurant',
  seafood_restaurant: 'seafood_restaurant',
  steak_house: 'steakhouse',
  steakhouse: 'steakhouse',

  // Casual dining
  pizza_restaurant: 'pizza_restaurant',
  pizzeria: 'pizza_restaurant',
  hamburger_restaurant: 'burger_restaurant',
  burger_restaurant: 'burger_restaurant',
  sandwich_shop: 'sandwich_restaurant',
  sandwich_restaurant: 'sandwich_restaurant',
  deli: 'sandwich_restaurant',
  fast_food_restaurant: 'fast_food',
  fast_food: 'fast_food',

  // Breakfast/brunch
  breakfast_restaurant: 'breakfast_restaurant',
  brunch_restaurant: 'breakfast_restaurant',
  diner: 'breakfast_restaurant',

  cafe: 'cafe',
  coffee_shop: 'cafe',
  bakery: 'bakery',
  bar: 'bar',
  wine_bar: 'bar',
  cocktail_bar: 'bar',
  pub: 'bar',
  night_club: 'bar',
  food_truck: 'food_truck',
  catering_service: 'catering',

  // Health & Wellness
  gym: 'gym',
  fitness_center: 'gym',
  health_club: 'gym',
  yoga_studio: 'yoga_studio',
  pilates_studio: 'yoga_studio',
  spa: 'spa',
  day_spa: 'spa',
  massage_therapist: 'massage',
  massage_therapy: 'massage',
  chiropractor: 'chiropractor',
  dentist: 'dentist',
  dental_clinic: 'dentist',
  doctor: 'doctor',
  medical_clinic: 'doctor',
  urgent_care_center: 'doctor',
  veterinarian: 'veterinarian',
  veterinary_care: 'veterinarian',
  animal_hospital: 'veterinarian',

  // Beauty & Personal Care
  hair_salon: 'hair_salon',
  beauty_salon: 'beauty_salon',
  hair_care: 'hair_salon',
  barber_shop: 'barber',
  barber: 'barber',
  nail_salon: 'nail_salon',
  tattoo_shop: 'tattoo',

  // Retail
  store: 'retail_store',
  retail: 'retail_store',
  clothing_store: 'clothing_store',
  boutique: 'clothing_store',
  jewelry_store: 'jewelry_store',
  florist: 'florist',
  flower_shop: 'florist',
  pet_store: 'pet_store',

  // Auto
  auto_repair: 'auto_repair',
  car_repair: 'auto_repair',
  mechanic: 'auto_repair',
  car_wash: 'car_wash',
  auto_detailing: 'car_wash',
  car_dealer: 'auto_dealer',
  auto_dealer: 'auto_dealer',
  tire_shop: 'tire_shop',

  // Professional Services
  lawyer: 'lawyer',
  law_firm: 'lawyer',
  attorney: 'lawyer',
  accountant: 'accountant',
  accounting_firm: 'accountant',
  real_estate_agency: 'real_estate',
  realtor: 'real_estate',
  insurance_agency: 'insurance',
  photographer: 'photography',
  photo_studio: 'photography',

  // Other
  hotel: 'hotel',
  motel: 'hotel',
  lodging: 'hotel',
  child_care_agency: 'daycare',
  preschool: 'daycare',
  tutoring_service: 'tutoring',
  music_school: 'music_lessons',
};

export function detectBusinessCategory(
  googleType: string | undefined,
  businessName: string
): BusinessCategory {
  // First try direct Google type mapping
  if (googleType) {
    const normalizedType = googleType.toLowerCase().replace(/-/g, '_');
    if (GOOGLE_TYPE_MAPPING[normalizedType]) {
      return GOOGLE_TYPE_MAPPING[normalizedType];
    }
  }

  // Then try keyword matching in business name
  const nameLower = businessName.toLowerCase();

  for (const [category, config] of Object.entries(CATEGORY_CONFIG)) {
    for (const keyword of config.keywords) {
      if (nameLower.includes(keyword)) {
        return category as BusinessCategory;
      }
    }
  }

  // Default fallback
  return 'other';
}

export function getCategoryInfo(category: BusinessCategory): CategoryInfo {
  return CATEGORY_CONFIG[category] || CATEGORY_CONFIG.other;
}

export function getCategoryDisplayName(category: BusinessCategory): string {
  return CATEGORY_CONFIG[category]?.displayName || 'Business';
}
